export const BLOCK_TIME_SECONDS = 2
export const RPC_FETCH_TIMEOUT_MS = 10_000
export const POLLING_INTERVAL_MS = 5_000
export const BACKEND_REFRESH_INTERVAL_MS = 300_000
export const STALENESS_THRESHOLD_SECONDS = 60
export const TPS_HISTORY_MAX_LENGTH = 20
